{% set version = "3.4.2" %}

package:
  name: conda-verify
  version: {{ version }}

source:
  url: https://github.com/conda/conda-verify/archive/{{ version }}.tar.gz
  sha256: d4b35ffedba9874a891982e37146a626126e61da23565977ce68170dcdf5908c

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation 
  entry_points:
    - conda-verify = conda_verify.cli:cli

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<3.12
    - six
    - jinja2 >=2.9
    - click >=6.7
    - pyyaml >=3.12
    # - backports.functools_lru_cache  # [py<33]
    - future >=0.12.0
    - tqdm
    - conda-package-handling

test:
  requires:
    - python {{ python_min }}
  imports:
    - conda_verify
  commands:
    - conda-verify --version
    - conda-verify --help

about:
  home: https://github.com/conda/conda-verify
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: tool for validating conda recipes and conda packages

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
    - mandeep
