{% set version = "3.1.1" %}

package:
  name: conda-verify
  version: {{ version }}

source:
  url: https://github.com/conda/conda-verify/archive/{{ version }}.tar.gz
  sha256: 465ff6d1c539e6d88a26b7564d2031739b98a5a0c8b50384724dcb707581f865

build:
  number: 1004
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - conda-verify = conda_verify.cli:cli

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - six
    - jinja2
    - click
    - pyyaml
    - backports.functools_lru_cache  # [py<33]
    - future

test:
  imports:
    - conda_verify
  commands:
    - conda-verify --version
    - conda-verify --help

about:
  home: https://github.com/conda/conda-verify
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: tool for validating conda recipes and conda packages

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
    - mandeep
