{% set version = "3.3.0" %}

package:
  name: conda-verify
  version: {{ version }}

source:
  url: https://github.com/conda/conda-verify/archive/{{ version }}.tar.gz
  sha256: 4aea8d873087f9cb7f68d45e7ef4f0dbd7c843148c28c22f28a0f47ea312ee2e

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - conda-verify = conda_verify.cli:cli

requirements:
  build:
    - python
    - pip
  run:
    - python
    - six
    - jinja2
    - click
    - pyyaml
    - backports.functools_lru_cache  # [py<33]
    - future

test:
  imports:
    - conda_verify
  commands:
    - conda-verify --version
    - conda-verify --help

about:
  home: https://github.com/conda/conda-verify
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: tool for validating conda recipes and conda packages

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
    - mandeep
