{% set version = "3.4.2" %}

package:
  name: conda-verify
  version: {{ version }}

source:
  url: https://github.com/conda/conda-verify/archive/{{ version }}.tar.gz
  sha256: d4b35ffedba9874a891982e37146a626126e61da23565977ce68170dcdf5908c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - conda-verify = conda_verify.cli:cli

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - six
    - jinja2
    - click
    - pyyaml
    - backports.functools_lru_cache  # [py<33]
    - future
    - tqdm

test:
  imports:
    - conda_verify
  commands:
    - conda-verify --version
    - conda-verify --help

about:
  home: https://github.com/conda/conda-verify
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: tool for validating conda recipes and conda packages

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
    - mandeep
